sonar.projectKey=Boss-1s_gdpy
sonar.organization=Boss-1s

sonar.projectName=gdpy

sonar.projectVersion=v0.0.0

sonar.sources=src/gdpy_oop,src/gdpy_struct

sonar.sourceEncoding=UTF-8

sonar.tests=tests

sonar.verbose=true

sonar.python.versions=3.15


sonar.python.pylint.reportPaths=pylint-report.json
sonar.python.coverage.reportPaths=coverage.xml

sonar.branch.name=main